apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-svc-deploy
  labels:
    app: vault-svc-app
spec:
  selector:
    matchLabels:
      app: vault-svc-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: vault-svc-app
    spec:
      containers:
        - name: vault-svc-app
          image: 590508189671.dkr.ecr.ap-south-1.amazonaws.com/vault-svc:preprod-latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/usr/src/app/vault-svc/secrets"
            readOnly: true
      serviceAccountName: preprod-secrets-manager-sa
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: preprod-vault-spc

              #resources:
              # requests:
              #cpu: "50m"
              #memory: "256Mi"
              #limits:
              #cpu: "100m"
              #memory: "512Mi"
