apiVersion: v1
kind: Service
metadata:
  name: main-api-service
  labels:
    app: main-api-app
spec:
  type: NodePort
  selector:
    app: main-api-app
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 3000
