apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-svc-deploy
  labels:
    app: payment-svc-app
spec:
  selector:
    matchLabels:
      app: payment-svc-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: payment-svc-app
    spec:
      containers:
        - name: payment-svc-app
          image: 590508189671.dkr.ecr.ap-south-1.amazonaws.com/payment-svc:preprod-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
