apiVersion: apps/v1
kind: Deployment
metadata:
  name: webadmin-app
  labels:
    app: webadmin-app
spec:
  selector:
    matchLabels:
      app: webadmin-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: webadmin-app
    spec:
      containers:
        - name: webadmin-app
          image: 590508189671.dkr.ecr.ap-south-1.amazonaws.com/web-admin:preprod-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
