apiVersion: v1
kind: Service
metadata:
  name: webadmin-service
  labels:
    app: webadmin-app
spec:
  type: NodePort
  selector:
    app: webadmin-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
