apiVersion: v1
kind: Service
metadata:
  name: scheduler-svc-service
  labels:
    app: scheduler-svc-app
spec:
  type: ClusterIP
  selector:
    app: scheduler-svc-app
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 3000
