apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-svc-deploy
  labels:
    app: erp-svc-app
spec:
  selector:
    matchLabels:
      app: erp-svc-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: erp-svc-app
    spec:
      containers:
        - name: erp-svc-app
          image: 590508189671.dkr.ecr.ap-south-1.amazonaws.com/erp-svc:preprod-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "100m"
              memory: "512Mi"
