apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributor-api-deploy
  labels:
    app: distributor-api-app
spec:
  selector:
    matchLabels:
      app: distributor-api-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: distributor-api-app
    spec:
      containers:
        - name: distributor-api-app
          image: 590508189671.dkr.ecr.ap-south-1.amazonaws.com/distributor-api:preprod-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "100m"
              memory: "512Mi"
