apiVersion: v1
kind: Service
metadata:
  name: distributor-api-service
  labels:
    app: distributor-api-app
spec:
  type: ClusterIP
  selector:
    app: distributor-api-app
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 3001
