apiVersion: v1
kind: Service
metadata:
  name: cms-svc-service
  labels:
    app: account-svc-app
spec:
  type: NodePort
  selector:
    app: cms-svc-app
  ports:
    - protocol: TCP
      name: http
      port: 5858
      targetPort: 5858
