apiVersion: apps/v1
kind: Deployment
metadata:
  name: b2b-deploy
  labels:
    app: b2b-app
spec:
  selector:
    matchLabels:
      app: b2b-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: b2b-app
    spec:
      containers:
        - name: b2b-app
          image: 590508189671.dkr.ecr.ap-south-1.amazonaws.com/b2b-api:preprod-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "100m"
              memory: "512Mi"
