apiVersion: v1
kind: Service
metadata:
  name: b2b-service
  labels:
    app: b2b-app
spec:
  type: NodePort
  selector:
    app: b2b-app
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 3000
